### PR TITLE
Fix team back navigation

### LINKED ISSUE #159: The sidebar is wrong when navigating to a teammate and navigating back
When you navigate to the Settings > Team page, then navigate to a teammate and either delete that user or click "Users" in the breadcrumbs, the page goes to the normal Users table view, filtered to the default `user` role (i.e. all teammates are missing, inducing heart atttacks), and the sidebar is still on Settings, exacerbating the user's distress. This is confusing because you're expecting to see teammates, not users, especially when deleting a teammate.

https://github.com/user-attachments/assets/09812ce4-437c-4c23-90ea-50a036262a3b

### PR DESCRIPTION
**Pull request by ezekg**
Closes #159. Refactors back navigation to prefer history, resolving issues where "back" wouldn't always mean "back."

### CODE REVIEW

File: src/components/back-button.tsx [hunk 1]
```diff
@@ -1,34 +1,25 @@
...
-  path: string
+  path?: string
   label?: string
   className?: string
-  preferHistory?: boolean
 }
 
 export default function BackButton({
-  path,
+  path = '..',
```
Comment (ezekg) [inline src/components/back-button.tsx]: We should probably just drop this prop because back should always be back, and if some other path is needed, the `GoToButton` should probably be used instead. This might also introduce issues where, if a `path` was supplied, history is used instead possibly resulting in an incorrect navigation.

**Review by Cazden — APPROVED** [review]
